### Creates a new patient
POST http://localhost:8001/patients
Content-Type: application/json

{
  "name" : "Sujay sahoo updated",
  "email": "sujaysahoo13@gmail.com",
  "address": "123 bankura west bengal",
  "dateOfBirth": "2003-09-16",
  "registeredDate": "2026-06-21"
}
###