### Creates a new patient
POST http://localhost:8004/api/patients
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name" : "Bhaivab adora",
  "email": "Bhaivab123@gmail.com",
  "address": "123 kolkata west bengal",
  "dateOfBirth": "2003-09-16",
  "registeredDate": "2026-06-21"
}
###