### update an exixting patient entity
PUT http://localhost:8004/api/patients/123e4567-a456-426614174001
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name" : "Sujit karmakar",
  "email": "sujitkarmakar12@gmail.com",
  "address": "123 Bishnupur west bengal",
  "dateOfBirth": "2003-09-16",
  "registeredDate": "2026-06-21"
}

###